/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package d3s.knowledges {

    [Bindable]
    [RemoteClass(alias="d3s.knowledges.Knowledge")]
    public class Knowledge {
		public var id:Number = 0;
    }
}