/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package d3s.playground.knowledges {
	import d3s.knowledges.Knowledge;
	import d3s.playground.vos.CrossingFields;
	import d3s.playground.vos.CrossingFieldsOccupancy;
	
	import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="d3s.playground.knowledges.CrossingKnowledge")]
    public class CrossingKnowledge extends Knowledge {
		
		public var blockedFields:CrossingFields;
		public var entries:CrossingFields;
		public var entriesOccupancy:CrossingFieldsOccupancy;
		public var exits:CrossingFields;
		public var exitsOccupancy:CrossingFieldsOccupancy;
		public var observedFields:CrossingFields;
		public var observedFieldsOccupancy:CrossingFieldsOccupancy;
		
		
		public function copyFrom(ck:CrossingKnowledge):void {
			entriesOccupancy = ck.entriesOccupancy;
			exitsOccupancy = ck.exitsOccupancy;
			observedFieldsOccupancy = ck.observedFieldsOccupancy;
		}
    }
}