/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package d3s.playground.knowledges {
	import d3s.knowledges.Knowledge;
	import d3s.playground.vos.Path;

    [Bindable]
    [RemoteClass(alias="d3s.playground.knowledges.RobotKnowledge")]
    public class RobotKnowledge extends Knowledge {
		public var path:Path = null;
		public var crossing:CrossingKnowledge = null;
		public var convoyRobot:RobotKnowledge = null;
		public var playground:PlaygroundKnowledge = null;
		public var speed:Number = 0;
		public var maximumSpeed:Number = 0;
		public var patienceThreshold:Number = 0;
		
		public var orientationPath:Path = null;
		
		public function copyFrom(r:RobotKnowledge):void {
			if (r) {
				patienceThreshold = r.patienceThreshold;
				maximumSpeed = r.maximumSpeed;
				speed = r.speed;
				if (path)
					path.copyFrom(r.path);
				else
					path = r.path;
			}
		}
    }
}