/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package d3s.playground.vos {
	import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="d3s.playground.vos.CrossingFieldsOccupancy")]
    public class CrossingFieldsOccupancy {
		
		public var occupancies:ArrayCollection;
		
		public function toString():String {
			if (occupancies) {
				var result:String = "[";
				for each (var o:Occupancy in occupancies) {
					if (o)
						result += o.toString() + ", ";
					else
						result += "[], ";
				}
				if (result.length > 1)
					result = result.substr(0, result.length-2);
				result += "]";
				return result;
			} else {
				return "[]";
			}
		}

    }
}