/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package d3s.playground.vos {
	import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="d3s.playground.vos.CrossingFields")]
    public class CrossingFields {
		public var fields:ArrayCollection;
    }
}