/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package d3s.playground.vos {

    [Bindable]
    [RemoteClass(alias="d3s.playground.vos.Field")]
    public class Field {
		public var color:int = 0;
		public var f:Number = 0.0;
		public var g:Number = 0.0;
		public var h:Number = 0.0;
		public var id:int = 0;
		public var parentField:Field = null;
		public var traversable:Boolean = true;
		public var x:int = 0;
		public var y:int = 0;
		
		public function toString():String {
			return id.toString();
		}
    }
}