/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package d3s.playground.vos {
	import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="d3s.playground.vos.Playground")]
    public class Playground {
		public var columnCount:Number = 0;
		public var crossings:ArrayCollection = null;
		public var disabledFields:ArrayCollection = null;
		public var enabledFields:ArrayCollection = null;
		public var fieldSize:Number = 0;
		public var playground:ArrayCollection = null;
		public var rowCount:Number = 0;
		public var pathFinder:Function;
		public var orientationGenerator:Function;
    }
}